version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
  postgres:
   image: postgres:14
   container_name: postgres
   restart: always
   environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: secret_9938
    POSTGRES_DB: kharcha_kaha

   ports:
    - '5432:5432'
   volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
    redis-data:
    postgres_data:

